name = "denopkg"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-10-31"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
